app:
  image:
    repository: 'onexc-apps/${project.name}'
    tag: ${project.version}
  nameOverride: ${project.name}
  routing:
    enabled: true 
  product: false
  operator:
    apm:
      enabled: false 
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: "onecx-document-management-ui"
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: ./DocumentManagementRemoteModule
          description: OneCX Document-Management Module
          note: OneCX Document-Management module auto import via MF operator
          type: MODULE
          productName: 'onecx-document-management'
    microservice:
      spec:
        productName: 'onecx-document-management'

product:
  info:
    data:
      name: "onecx-document-management"
      description: "OneCX Document Management"
      imageUrl: ""
      iconName: "pi-file-import"
      displayName: "OneCX Document-Management"
      basePath: "/documents"